/// Flutter icons Gomart
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Gomart
///      fonts:
///       - asset: fonts/Gomart.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Gomart {
  Gomart._();

  static const _kFontFam = 'Gomart';
  static const String? _kFontPkg = null;


  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filterOutline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profileHover = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartHover = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searchHover = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeHover = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walletHover = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messageHover = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationBell = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationIcon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
