import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:gomart/data/model/FlagCountryCode/flag_country_code.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'register_state.freezed.dart';

@freezed
class RegisterState with _$RegisterState {
  const factory RegisterState(
      {String? firstName,
      String? lastName,
      DateTime? dateOfBirth,
      String? phoneNumber,
      String? photoUrl,
        String? status,
      FlagCountryCodeModel? selectedCountry,
      }) = _RegisterState;

  factory RegisterState.initial() {
    return RegisterState(selectedCountry: FlagCountryCodeModel.getSupportedList[0]);
  }
}
