# This is a basic workflow to help you get started with Actions

name: CI flutter build android

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
    steps:
    - name: git Checkout
      uses: actions/checkout@v3
      
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.ACCESS_TOKEN_GITHUB}}    
        
    - name: Setup java environment
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        
    - name: Setting up flutter environment
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        
    - name: Download flutter app dependecies
      run: flutter pub get
      
    - name: Run all our tests
      run: flutter test
      
    - name: Build flutter apk
      run: flutter build apk --build-name=1.2.0+${GITHUB_SHA::6} --build-number=${{ steps.buildnumber.outputs.build_number }}
      
    - name: Navigate to where our apk is 
      run: cd build/app/outputs/flutter-apk/ && ls
      
    - name: Upload our apk artifact  
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        
  deploy_app_distribution:

    runs-on: ubuntu-latest

    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: android-apk
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: app_testers
        file: build/app/outputs/flutter-apk/app-release.apk
