# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build app
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
    steps:
      - name: git Checkout
        uses: actions/checkout@v3

      - name: Setup java environment
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setting up flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Download flutter app dependecies
        run: flutter pub get

      - name: Run all our tests
        run: flutter test